import { Router, Request, Response } from 'express';
import { execFile, exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs';
import * as path from 'path';
import pino from 'pino';
import { IAuditLogger } from '../../domain/interfaces/audit-logger';
import { requireAdmin } from './middleware/auth-middleware';

const execFileAsync = promisify(execFile);

const nsenter = async (cmd: string, args: string[] = [], timeoutMs = 20000): Promise<{ stdout: string; stderr: string }> => {
  return execFileAsync('nsenter', ['-t', '1', '-m', '-u', '-i', '-n', '-p', cmd, ...args], {
    timeout: timeoutMs,
    encoding: 'utf-8',
    env: { ...process.env, DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/var/run/dbus/system_bus_socket' },
  });
};

// systemctl needs D-Bus which uses Unix sockets — don't enter the network namespace
const nsenterSvc = async (cmd: string, args: string[] = [], timeoutMs = 20000): Promise<{ stdout: string; stderr: string }> => {
  return execFileAsync('nsenter', ['-t', '1', '-m', '-u', '-i', '-p', cmd, ...args], {
    timeout: timeoutMs,
    encoding: 'utf-8',
    env: { ...process.env, DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/var/run/dbus/system_bus_socket' },
  });
};

const HOST_STATE_FILE = '/proc/1/root/etc/open5gs-nms/frr-migration-state.json';
const HOST_FRR_CONF   = '/proc/1/root/etc/frr/frr.conf';
const HOST_DAEMONS    = '/proc/1/root/etc/frr/daemons';
const BACKUP_DIR      = '/proc/1/root/etc/open5gs-nms/frr-backup';

// ─── Types ────────────────────────────────────────────────────────────────────

export type MigrationPhase =
  | 'INIT' | 'BACKUP_CREATED' | 'FRR_INSTALLED' | 'TRANSIT_CONFIGURED'
  | 'NEIGHBOR_UP' | 'DUMMY_INTERFACES_CREATED' | 'SERVICE_DUAL_STACK_ACTIVE'
  | 'LEGACY_INTERFACES_REMOVED' | 'CUTOVER_COMPLETE';

export type Protocol = 'eigrp' | 'ospf' | 'bgp';

export interface ServiceMapping { service: string; ip: string; dummyName: string; }

export interface RouteFilter {
  id: string;
  name: string;
  direction: 'in' | 'out';
  action: 'permit' | 'deny';
  seq: number;
  prefixes: string[]; // CIDR strings e.g. ["10.0.0.0/8", "172.16.0.0/12"]
  description?: string;
}

export interface MigrationState {
  phase: MigrationPhase;
  protocol: Protocol | null;
  protocolConfig: Record<string, any> | null;
  mgmtInterface: string | null;
  transitInterface: string | null;
  transitCidr: string | null;
  servicePlaneInterface: string | null;
  serviceMappings: ServiceMapping[];
  routeFilters: RouteFilter[];
  routeFilterBackup?: RouteFilter[];
  backupTimestamp: string | null;
  log: Array<{ ts: string; phase: MigrationPhase; msg: string; ok: boolean }>;
  updatedAt: string;
}

// ─── State helpers ────────────────────────────────────────────────────────────

function loadState(): MigrationState {
  try {
    if (fs.existsSync(HOST_STATE_FILE)) {
      return JSON.parse(fs.readFileSync(HOST_STATE_FILE, 'utf-8'));
    }
  } catch {}
  return {
    phase: 'INIT', protocol: null, protocolConfig: null,
    mgmtInterface: null, transitInterface: null, transitCidr: null,
    servicePlaneInterface: null, serviceMappings: [], routeFilters: [],
    backupTimestamp: null, log: [], updatedAt: new Date().toISOString(),
  };
}

function saveState(state: MigrationState): void {
  const dir = path.dirname(HOST_STATE_FILE);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  state.updatedAt = new Date().toISOString();
  fs.writeFileSync(HOST_STATE_FILE, JSON.stringify(state, null, 2), 'utf-8');
}

function appendLog(state: MigrationState, phase: MigrationPhase, msg: string, ok: boolean): void {
  state.log.push({ ts: new Date().toISOString(), phase, msg, ok });
  if (state.log.length > 200) state.log = state.log.slice(-200);
}

// ─── FRR config generators ────────────────────────────────────────────────────

// Detect the installed FRR version string (e.g. "8.4.4") from vtysh output
async function detectFrrVersion(): Promise<string> {
  try {
    const { stdout } = await nsenter('vtysh', ['-c', 'show version']);
    const m = stdout.match(/FRRouting\s+(\d+\.\d+\.\d+)/);
    return m?.[1] ?? '9';
  } catch {
    return '9';
  }
}

// Get hostname for frr.conf
async function detectHostname(): Promise<string> {
  try {
    const { stdout } = await nsenter('hostname');
    return stdout.trim() || 'open5gs';
  } catch {
    return 'open5gs';
  }
}

function frrHeader(version: string, hostname: string): string[] {
  return [
    '!',
    '! Generated by Open5GS NMS',
    '!',
    `frr version ${version}`,
    'frr defaults traditional',
    `hostname ${hostname}`,
    'log syslog informational',
    'no ipv6 forwarding',
    'service integrated-vtysh-config',
    '!',
  ];
}

// Generate EIGRP config for Phase 3 (transit only, no VSIs yet)
function generateEigrpTransitConfig(cfg: Record<string, any>, transitNetCidr: string, version: string, hostname: string, mgmtIface: string): string {
  return [
    ...frrHeader(version, hostname),
    `router eigrp ${cfg.as}`,
    `  network ${transitNetCidr}`,
    `  passive-interface ${mgmtIface}`,
    'exit',
    '!',
    'end',
  ].join('\n');
}

function generateEigrpConfig(cfg: Record<string, any>, services: ServiceMapping[], transitIface: string, version: string, hostname: string, mgmtIface: string, filters: RouteFilter[] = []): string {
  // FRR 8.4.x eigrpd bug: redistribute connected and redistribute static are both broken.
  // Use explicit network statements for each VSI /32 instead.
  const passiveIfaces = [
    mgmtIface,
    ...services.map(s => s.dummyName),
  ].filter(Boolean);

  const inFilters  = filters.filter(f => f.direction === 'in');
  const outFilters = filters.filter(f => f.direction === 'out');
  const hasFilters = inFilters.length > 0 || outFilters.length > 0;

  const eigrpLines = [
    `router eigrp ${cfg.as}`,
    `  network ${cfg.transitCidr ?? '192.168.253.0/30'}`,
    ...services.map(s => `  network ${s.ip}/32`),
    ...passiveIfaces.map(i => `  passive-interface ${i}`),
  ];

  // eigrpd 8.4.4 does not implement distribute-list — filtering is done at zebra RIB level instead
  // (see generateEigrpFilterConfig for the ip protocol eigrp route-map approach)

  eigrpLines.push('exit', '!');

  const filterLines = generateEigrpFilterConfig(filters, transitIface);

  return [
    ...frrHeader(version, hostname),
    ...eigrpLines,
    ...filterLines,
    'end',
  ].join('\n');
}

function generateOspfConfig(cfg: Record<string, any>, services: ServiceMapping[], transitIface: string, transitCidr: string, version: string, hostname: string, filters: RouteFilter[] = []): string {
  const lines = [
    ...frrHeader(version, hostname),
    `router ospf ${cfg.processId}`,
    ...(cfg.routerId ? [`  ospf router-id ${cfg.routerId}`] : []),
    ...(cfg.passiveInterfaces ?? []).map((i: string) => `  passive-interface ${i}`),
  ];

  if (cfg.redistributeMethod === 'redistribute') {
    lines.push('  redistribute connected route-map OPEN5GS_SERVICES');
  } else {
    lines.push(`  network ${transitCidr} area ${cfg.area}`);
    for (const svc of services) lines.push(`  network ${svc.ip}/32 area ${cfg.area}`);
  }
  lines.push('exit', '!', `interface ${transitIface}`, `  ip ospf network ${cfg.networkType}`, `  ip ospf area ${cfg.area}`, '!');

  if (cfg.redistributeMethod === 'redistribute') {
    let seq = 10;
    for (const svc of services) {
      lines.push(`route-map OPEN5GS_SERVICES permit ${seq}`);
      lines.push(`  match interface ${svc.dummyName}`);
      seq += 10;
    }
    lines.push(`route-map OPEN5GS_SERVICES deny ${seq}`, '!');
  }

  // Wire NMS route filters via distribute-list on the OSPF process
  const inFilters  = filters.filter(f => f.direction === 'in');
  const outFilters = filters.filter(f => f.direction === 'out');
  if (inFilters.length > 0 || outFilters.length > 0) {
    // Re-open the router ospf block to add distribute-list
    lines.push(`router ospf ${cfg.processId}`);
    if (inFilters.length > 0)  lines.push(`  distribute-list route-map NMS_IN in`);
    if (outFilters.length > 0) lines.push(`  distribute-list route-map NMS_OUT out`);
    lines.push('exit', '!');
    lines.push(...generateRouteFilterConfig(filters, '', 'ospf'));
  }

  lines.push('end');
  return lines.join('\n');
}

function generateBgpConfig(cfg: Record<string, any>, services: ServiceMapping[], version: string, hostname: string, filters: RouteFilter[] = []): string {
  const lines = [
    ...frrHeader(version, hostname),
    `router bgp ${cfg.localAs}`,
    ...(services.length > 0 ? [`  bgp router-id ${services[0].ip}`] : []),
    `  neighbor ${cfg.peerIp} remote-as ${cfg.peerAs}`,
    `  neighbor ${cfg.peerIp} description Open5GS-NMS`,
    ...(cfg.ebgpMultihop > 1 ? [`  neighbor ${cfg.peerIp} ebgp-multihop ${cfg.ebgpMultihop}`] : []),
    '  !',
    '  address-family ipv4 unicast',
    ...services.map(svc => `    network ${svc.ip}/32`),
    ...(cfg.nextHopSelf ? [`    neighbor ${cfg.peerIp} next-hop-self`] : []),
    `    neighbor ${cfg.peerIp} activate`,
    ...(filters.filter(f => f.direction === 'in').length > 0  ? [`    neighbor ${cfg.peerIp} route-map NMS_IN in`]  : []),
    ...(filters.filter(f => f.direction === 'out').length > 0 ? [`    neighbor ${cfg.peerIp} route-map NMS_OUT out`] : []),
    '  exit-address-family',
    'exit',
    '!',
    ...generateRouteFilterConfig(filters, cfg.peerIp ?? '', 'bgp'),
    'end',
  ];
  return lines.join('\n');
}

async function generateFrrConfig(state: MigrationState): Promise<string> {
  const { protocolConfig, serviceMappings, transitInterface, transitCidr, protocol, mgmtInterface } = state;
  if (!protocolConfig || !transitInterface) return '';
  const version  = await detectFrrVersion();
  const hostname = await detectHostname();

  // Derive the network address from the transit CIDR (e.g. 192.168.253.2/30 -> 192.168.253.0/30)
  const transitNetCidr = (() => {
    if (!transitCidr) return '192.168.253.0/30';
    const [ip, prefix] = transitCidr.split('/');
    const prefixLen = parseInt(prefix);
    const ipParts = ip.split('.').map(Number);
    const mask = ~((1 << (32 - prefixLen)) - 1) >>> 0;
    const ipInt = ((ipParts[0] << 24) | (ipParts[1] << 16) | (ipParts[2] << 8) | ipParts[3]) >>> 0;
    const netInt = (ipInt & mask) >>> 0;
    const net = [(netInt >>> 24) & 0xff, (netInt >>> 16) & 0xff, (netInt >>> 8) & 0xff, netInt & 0xff].join('.');
    return `${net}/${prefixLen}`;
  })();

  if (protocol === 'eigrp') return generateEigrpConfig({ ...protocolConfig, transitCidr: transitNetCidr }, serviceMappings, transitInterface, version, hostname, mgmtInterface ?? '', state.routeFilters ?? []);
  if (protocol === 'ospf')  return generateOspfConfig(protocolConfig, serviceMappings, transitInterface, transitCidr ?? '', version, hostname, state.routeFilters ?? []);
  if (protocol === 'bgp')   return generateBgpConfig(protocolConfig, serviceMappings, version, hostname, state.routeFilters ?? []);
  return '';
}

// For EIGRP on FRR 8.4.4: eigrpd does NOT implement distribute-list filtering at all.
// The only working filter mechanism is zebra-level "ip protocol eigrp route-map"
// which filters routes as they're installed into/from the kernel RIB.
// IN  filter: controls what EIGRP-learned routes get installed into the kernel (received from Nexus)
// OUT filter: controls what routes zebra redistributes back out — NOTE: for outbound advertisement
//             filtering in EIGRP, the only real option at eigrpd level is to not advertise networks
//             at all. The "network" statements are the outbound filter — only listed networks advertise.
//             So for outbound, the network statements already act as an exact permit list.
function generateEigrpFilterConfig(filters: RouteFilter[], transitIface: string): string[] {
  if (!filters || filters.length === 0) return [];

  const inFilters  = filters.filter(f => f.direction === 'in').sort((a, b) => a.seq - b.seq);
  const outFilters = filters.filter(f => f.direction === 'out').sort((a, b) => a.seq - b.seq);

  if (inFilters.length === 0 && outFilters.length === 0) return [];

  const lines: string[] = ['!', '! Route filters (EIGRP — zebra RIB-level, eigrpd does not support distribute-list)'];

  // Build prefix-lists and route-maps for each direction
  for (const dir of ['in', 'out'] as const) {
    const dirFilters = dir === 'in' ? inFilters : outFilters;
    if (dirFilters.length === 0) continue;
    const rmName = `NMS_${dir.toUpperCase()}`;
    let seq = 5;
    for (const f of dirFilters) {
      const plName = `NMS_PL_${f.id.toUpperCase()}`;
      if (f.description) lines.push(`! ${f.description}`);
      for (const pfx of f.prefixes) {
        lines.push(`ip prefix-list ${plName} seq ${seq} ${f.action} ${pfx}`);
        seq += 5;
      }
      lines.push('!');
      lines.push(`route-map ${rmName} ${f.action} ${f.seq}`);
      if (f.description) lines.push(`  description ${f.description}`);
      lines.push(`  match ip address prefix-list ${plName}`);
      lines.push('!');
    }
    const lastSeq = (dirFilters[dirFilters.length - 1].seq ?? 10) + 10;
    lines.push(`route-map ${rmName} deny ${lastSeq}`);
    lines.push('!');
  }

  // Wire into zebra: "ip protocol eigrp route-map" filters EIGRP routes entering the kernel RIB
  if (inFilters.length > 0) {
    lines.push('! Apply inbound filter at zebra RIB level (controls routes learned from EIGRP neighbor)');
    lines.push('ip protocol eigrp route-map NMS_IN');
    lines.push('!');
  }

  if (outFilters.length > 0) {
    lines.push('! Note: outbound EIGRP advertisement is controlled by "network" statements above.');
    lines.push('! The NMS_OUT route-map is defined but outbound eigrpd filtering is not supported in FRR 8.4.4.');
    lines.push('!');
  }

  return lines;
}

// For OSPF/BGP: full route-map support is available.
function generateRouteFilterConfig(filters: RouteFilter[], peerIp: string, protocol: string): string[] {
  if (!filters || filters.length === 0) return [];
  const lines: string[] = ['!', '! Route filters'];

  const inFilters  = filters.filter(f => f.direction === 'in').sort((a, b) => a.seq - b.seq);
  const outFilters = filters.filter(f => f.direction === 'out').sort((a, b) => a.seq - b.seq);

  for (const dir of ['in', 'out'] as const) {
    const dirFilters = dir === 'in' ? inFilters : outFilters;
    if (dirFilters.length === 0) continue;
    const rmName = `NMS_${dir.toUpperCase()}`;

    for (const f of dirFilters) {
      const plName = `NMS_PL_${f.id.toUpperCase()}`;
      for (let i = 0; i < f.prefixes.length; i++) {
        lines.push(`ip prefix-list ${plName} seq ${(i + 1) * 5} ${f.action} ${f.prefixes[i]}`);
      }
      lines.push('!');
      lines.push(`route-map ${rmName} ${f.action} ${f.seq}`);
      if (f.description) lines.push(`  description ${f.description}`);
      if (f.prefixes.length > 0) lines.push(`  match ip address prefix-list ${plName}`);
      lines.push('!');
    }

    const lastSeq = (dirFilters[dirFilters.length - 1].seq ?? 10) + 10;
    lines.push(`route-map ${rmName} deny ${lastSeq}`);
    lines.push('!');
  }

  return lines;
}

function generateTransitNetplan(iface: string, cidr: string): string {
  return [
    '# Generated by Open5GS NMS FRR migration',
    'network:', '  version: 2', '  ethernets:',
    `    ${iface}:`, `      addresses: [${cidr}]`, '',
  ].join('\n');
}

function generateDummyNetplan(services: ServiceMapping[]): string {
  const lines = [
    '# Generated by Open5GS NMS FRR migration — service dummy interfaces',
    'network:', '  version: 2', '  dummy-devices:',
  ];
  for (const svc of services) {
    lines.push(`    ${svc.dummyName}:`, `      addresses: [${svc.ip}/32]`);
  }
  lines.push('');
  return lines.join('\n');
}

// ─── Parsers ──────────────────────────────────────────────────────────────────

function parseEigrpNeighbors(raw: string): any[] {
  // Format: H   Address           Interface  Hold  Uptime  SRTT  RTO  Q  Seq
  //         0   192.168.253.1     ens20      12    0       0     2    0  22393
  // H column is an integer index; skip lines that don't start with a digit
  const result: any[] = [];
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || !/^\d/.test(trimmed)) continue;
    const parts = trimmed.split(/\s+/);
    if (parts.length < 3) continue;
    const ip    = parts[1];
    const iface = parts[2];
    const hold  = parts[3] ?? '';
    const uptime = parts[4] ?? '';
    // Basic IP validation
    if (!/^\d+\.\d+\.\d+\.\d+$/.test(ip)) continue;
    result.push({ ip, iface, holdTime: hold, uptime, state: 'active' });
  }
  return result;
}

function parseOspfNeighbors(raw: string): any[] {
  // Format: Neighbor ID  Pri  State     Dead Time  Address         Interface
  //         10.0.0.1     1    Full/DR   00:00:35   192.168.1.2     ens20
  const result: any[] = [];
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || !/^\d+\.\d+\.\d+\.\d+/.test(trimmed)) continue;
    const parts = trimmed.split(/\s+/);
    if (parts.length < 6) continue;
    result.push({ id: parts[0], priority: parts[1], state: parts[2], deadTime: parts[3], address: parts[4], iface: parts[5] });
  }
  return result;
}

function parseBgpSummary(raw: string): any[] {
  // Format: Neighbor  V  AS  MsgRcvd  MsgSent  TblVer  InQ  OutQ  Up/Down  State/PfxRcd
  const result: any[] = [];
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || !/^\d+\.\d+\.\d+\.\d+/.test(trimmed)) continue;
    const parts = trimmed.split(/\s+/);
    if (parts.length < 9) continue;
    const state = parts.slice(8).join(' ');
    result.push({ peer: parts[0], as: parts[2], uptime: parts[8], state: isNaN(Number(state.trim())) ? state.trim() : 'Established' });
  }
  return result;
}

function parseEigrpTopology(raw: string): any[] {
  // Format: P  10.0.1.0/24, 1 successors, FD is 5376
  //              via 192.168.253.1 (5376/2816), ens20
  const result: any[] = [];
  let current: any = null;
  for (const line of raw.split('\n')) {
    const prefixMatch = line.match(/^[PAUQR]\s+(\S+),/);
    if (prefixMatch) {
      current = { prefix: prefixMatch[1], via: [] };
      result.push(current);
    } else if (current) {
      const viaMatch = line.match(/via\s+(\S+)\s+\(([^)]+)\),\s*(\S+)/);
      if (viaMatch) current.via.push({ nexthop: viaMatch[1], metric: viaMatch[2], iface: viaMatch[3] });
    }
  }
  return result;
}

function parseRoutes(raw: string): any[] {
  const result: any[] = [];
  for (const line of raw.split('\n')) {
    const m = line.match(/^([A-Z>*\s]+)\s+(\S+\/\d+)/);
    if (m) result.push({ flags: m[1].trim(), prefix: m[2] });
  }
  return result;
}

// ─── Router ───────────────────────────────────────────────────────────────────

export function createFrrRouter(logger: pino.Logger, auditLogger: IAuditLogger): Router {
  const router = Router();

  router.get('/detect', async (_req: Request, res: Response) => {
    try {
      const { stdout: which } = await nsenter('which', ['vtysh']).catch(() => ({ stdout: '' }));
      const installed = which.trim().length > 0;
      if (!installed) return res.json({ success: true, installed: false, active: false, protocol: null, neighbors: [], routes: [] });

      const activeOut = await new Promise<string>(resolve => {
        const c = exec(`nsenter -t 1 -m -u -i -p -- systemctl is-active frr`);
        let out = '';
        c.stdout?.on('data', (d: Buffer) => { out += d.toString(); });
        c.on('close', () => resolve(out.trim()));
      });
      const active = activeOut === 'active';
      if (!active) return res.json({ success: true, installed: true, active: false, protocol: null, neighbors: [], routes: [] });

      const { stdout: runCfg } = await nsenter('vtysh', ['-c', 'show running-config']).catch(() => ({ stdout: '' }));
      let protocol: Protocol | null = null;
      if (/^router eigrp/m.test(runCfg))   protocol = 'eigrp';
      else if (/^router ospf/m.test(runCfg)) protocol = 'ospf';
      else if (/^router bgp/m.test(runCfg))  protocol = 'bgp';

      let neighbors: any[] = [];
      let topology: any[] = [];
      if (protocol === 'eigrp') {
        const { stdout: nbOut }   = await nsenter('vtysh', ['-c', 'show ip eigrp neighbors']).catch(() => ({ stdout: '' }));
        const { stdout: topoOut } = await nsenter('vtysh', ['-c', 'show ip eigrp topology']).catch(() => ({ stdout: '' }));
        neighbors = parseEigrpNeighbors(nbOut);
        topology  = parseEigrpTopology(topoOut);
      } else if (protocol === 'ospf') {
        const { stdout } = await nsenter('vtysh', ['-c', 'show ip ospf neighbor']).catch(() => ({ stdout: '' }));
        neighbors = parseOspfNeighbors(stdout);
      } else if (protocol === 'bgp') {
        const { stdout } = await nsenter('vtysh', ['-c', 'show bgp summary']).catch(() => ({ stdout: '' }));
        neighbors = parseBgpSummary(stdout);
      }

      const { stdout: routeOut } = await nsenter('vtysh', ['-c', 'show ip route']).catch(() => ({ stdout: '' }));
      res.json({ success: true, installed, active, protocol, runningConfig: runCfg, neighbors, topology, routes: parseRoutes(routeOut) });
    } catch (err) {
      logger.error({ err: String(err) }, 'frr detect error');
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  router.get('/interfaces', async (_req: Request, res: Response) => {
    try {
      const { stdout } = await nsenter('ip', ['-j', 'addr', 'show']);
      const ifaces: any[] = JSON.parse(stdout);
      const { stdout: routeOut } = await nsenter('ip', ['-j', 'route', 'show', 'default']).catch(() => ({ stdout: '[]' }));
      const defaultRoutes: any[] = JSON.parse(routeOut);
      const mgmtIface = defaultRoutes[0]?.dev ?? null;
      const result = ifaces
        .filter(i => !i.ifname?.startsWith('lo') && !i.ifname?.startsWith('docker') && !i.ifname?.startsWith('br-'))
        .map(i => ({
          name: i.ifname,
          mac: i.address,
          state: i.operstate,
          addresses: (i.addr_info ?? []).filter((a: any) => a.family === 'inet').map((a: any) => `${a.local}/${a.prefixlen}`),
          isMgmt: i.ifname === mgmtIface,
        }));
      res.json({ success: true, interfaces: result, mgmtInterface: mgmtIface });
    } catch (err) {
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  router.get('/state', (_req: Request, res: Response) => {
    try { res.json({ success: true, state: loadState() }); }
    catch (err) { res.status(500).json({ success: false, error: String(err) }); }
  });

  router.post('/state/reset', requireAdmin, (_req: Request, res: Response) => {
    try {
      const fresh: MigrationState = {
        phase: 'INIT', protocol: null, protocolConfig: null,
        mgmtInterface: null, transitInterface: null, transitCidr: null,
        servicePlaneInterface: null, serviceMappings: [], routeFilters: [],
        backupTimestamp: null, log: [], updatedAt: new Date().toISOString(),
      };
      saveState(fresh);
      res.json({ success: true, state: fresh });
    } catch (err) { res.status(500).json({ success: false, error: String(err) }); }
  });

  router.get('/preview-config', async (_req: Request, res: Response) => {
    try { res.json({ success: true, config: await generateFrrConfig(loadState()) }); }
    catch (err) { res.status(500).json({ success: false, error: String(err) }); }
  });

  router.post('/migration/configure', requireAdmin, (req: Request, res: Response) => {
    try {
      const state = loadState();
      const { mgmtInterface, transitInterface, transitCidr, servicePlaneInterface, serviceMappings, protocol, protocolConfig } = req.body;
      state.mgmtInterface = mgmtInterface;
      state.transitInterface = transitInterface;
      state.transitCidr = transitCidr;
      state.servicePlaneInterface = servicePlaneInterface;
      state.serviceMappings = serviceMappings ?? [];
      state.protocol = protocol;
      state.protocolConfig = protocolConfig;
      saveState(state);
      res.json({ success: true, state });
    } catch (err) { res.status(500).json({ success: false, error: String(err) }); }
  });

  router.post('/migration/backup', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    try {
      if (!fs.existsSync(BACKUP_DIR)) fs.mkdirSync(BACKUP_DIR, { recursive: true });
      const ts = new Date().toISOString().replace(/[:.]/g, '-');
      // Backup netplan
      await nsenter('cp', ['-r', '/etc/netplan', `${BACKUP_DIR.replace('/proc/1/root', '')}/netplan-${ts}`]);
      // Backup FRR config + daemons if they exist
      if (fs.existsSync(HOST_FRR_CONF)) {
        fs.copyFileSync(HOST_FRR_CONF, `${BACKUP_DIR}/frr.conf-${ts}`);
      }
      if (fs.existsSync(HOST_DAEMONS)) {
        fs.copyFileSync(HOST_DAEMONS, `${BACKUP_DIR}/daemons-${ts}`);
      }
      // Backup routing table + interface state
      const { stdout: routeTable } = await nsenter('ip', ['route', 'show', 'table', 'all']);
      fs.writeFileSync(`${BACKUP_DIR}/routes-${ts}.txt`, routeTable);
      const { stdout: ifaceState } = await nsenter('ip', ['-j', 'addr', 'show']);
      fs.writeFileSync(`${BACKUP_DIR}/interfaces-${ts}.json`, ifaceState);
      state.phase = 'BACKUP_CREATED';
      state.backupTimestamp = ts;
      appendLog(state, 'BACKUP_CREATED', `Backup created at ${ts}`, true);
      saveState(state);
      await auditLogger.log({ action: 'frr_backup', user, details: `ts: ${ts}`, success: true });
      res.json({ success: true, state, backupTimestamp: ts });
    } catch (err) {
      appendLog(state, state.phase, `Backup failed: ${String(err)}`, false);
      saveState(state);
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  router.post('/migration/install-frr', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    if (state.phase !== 'BACKUP_CREATED') return res.status(400).json({ success: false, error: `Invalid phase: ${state.phase}` });

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.flushHeaders();
    const write = (msg: string) => res.write(msg);

    try {
      write('Checking if FRR is already installed...\n');
      const { stdout: which } = await nsenter('which', ['vtysh']).catch(() => ({ stdout: '' }));
      if (!which.trim()) {
        write('Installing FRR...\n');
        await new Promise<void>((resolve, reject) => {
          const child = exec(`nsenter -t 1 -m -u -i -n -p -- bash -c 'DEBIAN_FRONTEND=noninteractive apt-get install -y frr frr-pythontools'`);
          child.stdout?.on('data', (d: Buffer) => write(d.toString()));
          child.stderr?.on('data', (d: Buffer) => write(d.toString()));
          child.on('close', code => code === 0 ? resolve() : reject(new Error(`apt exit ${code}`)));
        });
      } else {
        write('FRR already installed.\n');
      }

      write(`\nEnabling daemons for ${state.protocol}...\n`);
      if (fs.existsSync(HOST_DAEMONS)) {
        let d = fs.readFileSync(HOST_DAEMONS, 'utf-8');
        d = d.replace(/^zebra=.*/m, 'zebra=yes');
        if (state.protocol === 'eigrp') d = d.replace(/^eigrpd=.*/m, 'eigrpd=yes');
        if (state.protocol === 'ospf')  d = d.replace(/^ospfd=.*/m,  'ospfd=yes');
        if (state.protocol === 'bgp')   d = d.replace(/^bgpd=.*/m,   'bgpd=yes');
        fs.writeFileSync(HOST_DAEMONS, d, 'utf-8');
        write('Daemons file updated.\n');
      }

      write('\nStarting FRR...\n');
      await new Promise<void>((resolve, reject) => {
        exec(`nsenter -t 1 -m -u -i -p -- systemctl enable frr`, (err) => err ? reject(err) : resolve());
      });
      await new Promise<void>((resolve, reject) => {
        exec(`nsenter -t 1 -m -u -i -p -- systemctl restart frr`, (err) => err ? reject(err) : resolve());
      });

      const active = await new Promise<boolean>(resolve => {
        const c = exec(`nsenter -t 1 -m -u -i -p -- systemctl is-active frr`);
        let out = '';
        c.stdout?.on('data', (d: Buffer) => { out += d.toString(); });
        c.on('close', () => resolve(out.trim() === 'active'));
      });
      if (!active) throw new Error('FRR service did not start');

      state.phase = 'FRR_INSTALLED';
      appendLog(state, 'FRR_INSTALLED', 'FRR installed and running', true);
      saveState(state);
      await auditLogger.log({ action: 'frr_install', user, details: 'success', success: true });
      write('\n✅ FRR installed and running.\n');
      res.end();
    } catch (err) {
      appendLog(state, state.phase, `Install failed: ${String(err)}`, false);
      saveState(state);
      write(`\n❌ Error: ${String(err)}\n`);
      res.end();
    }
  });

  router.post('/migration/transit', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    if (state.phase !== 'FRR_INSTALLED') return res.status(400).json({ success: false, error: `Invalid phase: ${state.phase}` });

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.flushHeaders();
    const write = (msg: string) => res.write(msg);

    try {
      const content = generateTransitNetplan(state.transitInterface!, state.transitCidr!);
      fs.writeFileSync('/proc/1/root/etc/netplan/60-open5gs-transit.yaml', content, { encoding: 'utf-8', mode: 0o600 });
      write(`Written netplan for ${state.transitInterface} → ${state.transitCidr}\n`);
      write('Applying via netplan apply...\n');
      await nsenter('netplan', ['apply']);

      // Retry up to 15s — netplan apply returns before kernel finishes bringing iface up
      const targetIp = state.transitCidr!.split('/')[0];
      let ipFound = false;
      for (let attempt = 0; attempt < 15; attempt++) {
        await new Promise(r => setTimeout(r, 1000));
        const { stdout: ipCheck } = await nsenter('ip', ['addr', 'show', state.transitInterface!]).catch(() => ({ stdout: '' }));
        if (ipCheck.includes(targetIp)) { ipFound = true; break; }
        write(`Waiting for ${targetIp} on ${state.transitInterface}... (${attempt + 1}s)\n`);
      }
      if (!ipFound) throw new Error(`Timed out waiting for ${targetIp} on ${state.transitInterface} after 15s`);
      state.phase = 'TRANSIT_CONFIGURED';
      appendLog(state, 'TRANSIT_CONFIGURED', `${state.transitInterface} → ${state.transitCidr}`, true);
      saveState(state);
      await auditLogger.log({ action: 'frr_transit', user, details: `${state.transitInterface} ${state.transitCidr}`, success: true });
      write('\n✅ Transit interface configured.\n');
      res.end();
    } catch (err) {
      appendLog(state, state.phase, `Transit failed: ${String(err)}`, false);
      saveState(state);
      write(`\n❌ Error: ${String(err)}\n`);
      res.end();
    }
  });

  router.post('/migration/neighbor', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    if (state.phase !== 'TRANSIT_CONFIGURED') return res.status(400).json({ success: false, error: `Invalid phase: ${state.phase}` });

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.flushHeaders();
    const write = (msg: string) => res.write(msg);

    try {
      write('Generating FRR config (transit-only — VSIs not yet created)...\n');
      const version  = await detectFrrVersion();
      const hostname = await detectHostname();
      const transitNetCidr = (() => {
        const cidr = state.transitCidr ?? '192.168.253.0/30';
        const [ip, prefix] = cidr.split('/');
        const prefixLen = parseInt(prefix);
        const ipParts = ip.split('.').map(Number);
        const mask = ~((1 << (32 - prefixLen)) - 1) >>> 0;
        const ipInt = ((ipParts[0] << 24) | (ipParts[1] << 16) | (ipParts[2] << 8) | ipParts[3]) >>> 0;
        const netInt = (ipInt & mask) >>> 0;
        const net = [(netInt >>> 24) & 0xff, (netInt >>> 16) & 0xff, (netInt >>> 8) & 0xff, netInt & 0xff].join('.');
        return `${net}/${prefixLen}`;
      })();
      const config = state.protocol === 'eigrp' && state.protocolConfig
        ? generateEigrpTransitConfig(state.protocolConfig, transitNetCidr, version, hostname, state.mgmtInterface ?? '')
        : await generateFrrConfig(state);
      write(config + '\n\n');

      write('Writing /etc/frr/frr.conf...\n');
      fs.writeFileSync(HOST_FRR_CONF, config, 'utf-8');

      write('Restarting FRR (full restart required for new neighbor config)...\n');
      // Use exec with shell as fallback — nsenterSvc sometimes fails with D-Bus in certain container configs
      await new Promise<void>((resolve, reject) => {
        const child = exec(`nsenter -t 1 -m -u -i -p -- systemctl restart frr`);
        child.on('close', code => {
          if (code === 0) resolve();
          else reject(new Error(`systemctl restart frr exited ${code}`));
        });
      });

      // Wait for FRR to come back up
      write('Waiting for FRR to start...\n');
      for (let i = 0; i < 10; i++) {
        await new Promise(r => setTimeout(r, 1000));
        const isActive = await new Promise<boolean>(resolve => {
          const c = exec(`nsenter -t 1 -m -u -i -p -- systemctl is-active frr`);
          let out = '';
          c.stdout?.on('data', (d: Buffer) => { out += d.toString(); });
          c.on('close', () => resolve(out.trim() === 'active'));
        });
        if (isActive) { write('FRR is active.\n'); break; }
        write(`  waiting... (${i + 1}s)\n`);
      }

      write('\nFRR config written and service restarted.\n');
      write('Click "Refresh" or wait — the wizard will poll for neighbor establishment every 5 seconds.\n');

      await auditLogger.log({ action: 'frr_neighbor_config', user, details: `protocol: ${state.protocol}`, success: true });
      res.end();
    } catch (err) {
      write(`\n\u274c Error: ${String(err)}\n`);
      res.end();
    }
  });

  router.post('/migration/validate-neighbor', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    try {
      let neighborUp = false;
      let detail = '';
      if (state.protocol === 'eigrp') {
        const { stdout } = await nsenter('vtysh', ['-c', 'show ip eigrp neighbors']).catch(() => ({ stdout: '' }));
        const n = parseEigrpNeighbors(stdout);
        neighborUp = n.length > 0;
        detail = neighborUp ? `${n.length} EIGRP neighbor(s)` : 'No EIGRP neighbors yet';
      } else if (state.protocol === 'ospf') {
        const { stdout } = await nsenter('vtysh', ['-c', 'show ip ospf neighbor']).catch(() => ({ stdout: '' }));
        const n = parseOspfNeighbors(stdout);
        neighborUp = n.some(x => x.state?.includes('Full'));
        detail = neighborUp ? 'OSPF FULL' : `OSPF: ${n[0]?.state ?? 'no neighbor'}`;
      } else if (state.protocol === 'bgp') {
        const { stdout } = await nsenter('vtysh', ['-c', 'show bgp summary']).catch(() => ({ stdout: '' }));
        const n = parseBgpSummary(stdout);
        neighborUp = n.some(x => x.state === 'Established');
        detail = neighborUp ? 'BGP Established' : `BGP: ${n[0]?.state ?? 'no peer'}`;
      }
      if (neighborUp && state.phase === 'TRANSIT_CONFIGURED') {
        state.phase = 'NEIGHBOR_UP';
        appendLog(state, 'NEIGHBOR_UP', detail, true);
        saveState(state);
        await auditLogger.log({ action: 'frr_neighbor_up', user, details: detail, success: true });
      }
      res.json({ success: true, neighborUp, detail, state });
    } catch (err) {
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  router.post('/migration/dummies', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    if (state.phase !== 'NEIGHBOR_UP') return res.status(400).json({ success: false, error: `Invalid phase: ${state.phase}` });
    try {
      fs.writeFileSync('/proc/1/root/etc/netplan/61-open5gs-dummies.yaml', generateDummyNetplan(state.serviceMappings), { encoding: 'utf-8', mode: 0o600 });
      await nsenter('netplan', ['apply']);
      const { stdout: ipOut } = await nsenter('ip', ['addr', 'show']);
      const missing = state.serviceMappings.filter(svc => !ipOut.includes(svc.ip));
      if (missing.length > 0) throw new Error(`Missing: ${missing.map(m => m.dummyName).join(', ')}`);

      // Now that VSIs exist, write the full FRR config with network statements for each /32
      const fullConfig = await generateFrrConfig(state);
      fs.writeFileSync(HOST_FRR_CONF, fullConfig, 'utf-8');
      await new Promise<void>((resolve, reject) => {
        exec(`nsenter -t 1 -m -u -i -p -- systemctl restart frr`, (err) => err ? reject(err) : resolve());
      });
      // Wait for FRR to restart
      for (let i = 0; i < 10; i++) {
        await new Promise(r => setTimeout(r, 1000));
        const isActive = await new Promise<boolean>(resolve => {
          const c = exec(`nsenter -t 1 -m -u -i -p -- systemctl is-active frr`);
          let out = ''; c.stdout?.on('data', (d: Buffer) => { out += d.toString(); });
          c.on('close', () => resolve(out.trim() === 'active'));
        });
        if (isActive) break;
      }

      state.phase = 'DUMMY_INTERFACES_CREATED';
      appendLog(state, 'DUMMY_INTERFACES_CREATED', `${state.serviceMappings.length} dummies created`, true);
      saveState(state);
      await auditLogger.log({ action: 'frr_dummies', user, details: state.serviceMappings.map(s => s.dummyName).join(', '), success: true });
      res.json({ success: true, state });
    } catch (err) {
      appendLog(state, state.phase, `Dummies failed: ${String(err)}`, false);
      saveState(state);
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  router.post('/migration/advertise', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    if (state.phase !== 'DUMMY_INTERFACES_CREATED') return res.status(400).json({ success: false, error: `Invalid phase: ${state.phase}` });
    try {
      // Check kernel routing table (ip route) for connected /32s
      const { stdout: kernelRoutes } = await nsenter('ip', ['route', 'show']).catch(() => ({ stdout: '' }));
      // Also check vtysh routing table
      const { stdout: frrRoutes } = await nsenter('vtysh', ['-c', 'show ip route']).catch(() => ({ stdout: '' }));
      const combined = kernelRoutes + '\n' + frrRoutes;

      const missing = state.serviceMappings.filter(s => !combined.includes(s.ip));

      // Management leak check — look in FRR routes only
      if (state.mgmtInterface) {
        const { stdout: mgmtOut } = await nsenter('ip', ['-j', 'addr', 'show', state.mgmtInterface]).catch(() => ({ stdout: '[]' }));
        try {
          const parsed = JSON.parse(mgmtOut);
          const mgmtIps = (parsed[0]?.addr_info ?? []).filter((a: any) => a.family === 'inet').map((a: any) => a.local);
          const leaked = mgmtIps.filter((ip: string) => frrRoutes.includes(ip));
          if (leaked.length > 0) {
            return res.status(400).json({ success: false, error: `Management IP ${leaked[0]} is being advertised via FRR — check passive-interface config.` });
          }
        } catch {}
      }

      if (missing.length > 0) {
        return res.json({
          success: false, advertised: false, missing: missing.map(m => m.ip),
          message: `These IPs not found in routing table: ${missing.map(m => m.ip).join(', ')}\n\nIf VSIs are up and FRR is redistributing connected routes, you can skip this check.`,
        });
      }

      state.phase = 'SERVICE_DUAL_STACK_ACTIVE';
      appendLog(state, 'SERVICE_DUAL_STACK_ACTIVE', `All ${state.serviceMappings.length} service IPs verified in routing table`, true);
      saveState(state);
      await auditLogger.log({ action: 'frr_advertise', user, details: 'verified', success: true });
      res.json({ success: true, state, advertised: true });
    } catch (err) {
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  router.post('/migration/cutover', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    if (state.phase !== 'SERVICE_DUAL_STACK_ACTIVE') return res.status(400).json({ success: false, error: `Invalid phase: ${state.phase}` });

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.flushHeaders();
    const write = (msg: string) => res.write(msg);

    try {
      // Read all existing netplan files to understand current state
      const netplanHostDir = '/proc/1/root/etc/netplan';
      const files = fs.readdirSync(netplanHostDir).filter(f => f.endsWith('.yaml') || f.endsWith('.yml')).sort();
      write(`Found netplan files: ${files.join(', ')}\n`);

      // Collect all interface configs from existing files, excluding our generated ones
      const generatedFiles = ['60-open5gs-transit.yaml', '61-open5gs-dummies.yaml', '62-open5gs-cutover.yaml'];

      // Parse existing files to find mgmt interface config
      // We'll build a unified config that:
      //   1. Keeps mgmt interface exactly as-is
      //   2. Removes service IPs from the service plane interface
      //   3. Adds transit /30 to transit interface
      //   4. Adds dummy VSI interfaces
      // Then replaces ALL netplan files with this one unified file

      const mgmt  = state.mgmtInterface!;
      const transit = state.transitInterface!;
      const svcIface = state.servicePlaneInterface!;

      // Find how mgmt is configured (DHCP or static)
      let mgmtConfig = '      dhcp4: true';
      for (const f of files) {
        if (generatedFiles.includes(f)) continue;
        try {
          const content = fs.readFileSync(`${netplanHostDir}/${f}`, 'utf-8');
          // If this file configures the mgmt interface
          if (content.includes(mgmt + ':')) {
            const dhcp4 = content.match(new RegExp(`${mgmt}:[\\s\\S]*?dhcp4:\\s*(true|false)`));
            const staticAddrs = content.match(new RegExp(`${mgmt}:[\\s\\S]*?addresses:[\\s\\S]*?- ["']?([\\d./]+)["']?`));
            if (dhcp4) mgmtConfig = `      dhcp4: ${dhcp4[1]}`;
            else if (staticAddrs) mgmtConfig = `      dhcp4: false\n      addresses: [${staticAddrs[1]}]`;
          }
        } catch {}
      }

      write(`\nMgmt interface (${mgmt}): will preserve existing config\n`);
      write(`Transit interface (${transit}): ${state.transitCidr}\n`);
      write(`Service plane (${svcIface}): removing all service IPs\n`);
      write(`VSIs: ${state.serviceMappings.map(s => s.dummyName).join(', ')}\n\n`);

      // Build unified netplan
      const lines = [
        '# Managed by Open5GS NMS — generated at FRR L3 cutover',
        '# Do not manually edit; use the NMS FRR/L3 Routing page to reconfigure',
        'network:',
        '  version: 2',
        '  ethernets:',
        `    ${mgmt}:`,
        mgmtConfig,
        `    ${transit}:`,
        `      addresses: [${state.transitCidr}]`,
      ];

      // Keep svcIface defined but with no addresses (keeps it up for other uses)
      if (svcIface && svcIface !== transit && svcIface !== mgmt) {
        lines.push(`    ${svcIface}:`);
        lines.push('      dhcp4: false');
        lines.push('      addresses: []');
      }

      // Dummy VSI interfaces
      if (state.serviceMappings.length > 0) {
        lines.push('  dummy-devices:');
        for (const svc of state.serviceMappings) {
          lines.push(`    ${svc.dummyName}:`);
          lines.push(`      addresses: [${svc.ip}/32]`);
        }
      }

      lines.push('');
      const unified = lines.join('\n');
      write('Generated unified netplan:\n');
      write(unified + '\n');

      // Write unified config
      const unifiedPath = `${netplanHostDir}/60-open5gs-managed.yaml`;
      fs.writeFileSync(unifiedPath, unified, { encoding: 'utf-8', mode: 0o600 });
      write('Written 60-open5gs-managed.yaml\n');

      // Remove old files that would conflict:
      // - Any file that configures the service plane interface with the old IPs
      // - Our own generated migration files
      const toRemove = [...generatedFiles];
      for (const f of files) {
        if (f === '60-open5gs-managed.yaml') continue;
        if (generatedFiles.includes(f)) continue;
        try {
          const content = fs.readFileSync(`${netplanHostDir}/${f}`, 'utf-8');
          if (content.includes(svcIface + ':') && state.serviceMappings.some(s => content.includes(s.ip))) {
            toRemove.push(f);
          }
        } catch {}
      }

      for (const f of toRemove) {
        const fp = `${netplanHostDir}/${f}`;
        if (fs.existsSync(fp)) {
          // Backup before removing
          fs.copyFileSync(fp, `${BACKUP_DIR}/${f}.pre-cutover`);
          fs.unlinkSync(fp);
          write(`Removed ${f} (backed up)\n`);
        }
      }

      write('\nApplying unified netplan...\n');
      await nsenter('netplan', ['apply']);

      // Verify svc interface no longer has the old IPs
      await new Promise(r => setTimeout(r, 2000));
      const { stdout: ipOut } = await nsenter('ip', ['addr', 'show', svcIface]).catch(() => ({ stdout: '' }));
      const stillPresent = state.serviceMappings.filter(s => ipOut.includes(s.ip));
      if (stillPresent.length > 0) {
        write(`\n⚠️  Warning: ${stillPresent.map(s => s.ip).join(', ')} still on ${svcIface} — may need manual removal\n`);
      } else {
        write(`✅ Service IPs removed from ${svcIface}\n`);
      }

      state.phase = 'CUTOVER_COMPLETE';
      appendLog(state, 'CUTOVER_COMPLETE', `Unified netplan applied, service IPs removed from ${svcIface}`, true);
      saveState(state);
      await auditLogger.log({ action: 'frr_cutover', user, details: `unified netplan, removed ${svcIface} service IPs`, success: true });
      write('\n✅ Cutover complete. Unified netplan is now managing all interfaces.\n');
      res.end();
    } catch (err) {
      appendLog(state, state.phase, `Cutover failed: ${String(err)}`, false);
      saveState(state);
      write(`\n❌ Error: ${String(err)}\n`);
      res.end();
    }
  });

  router.post('/migration/confirm', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    try {
      await nsenter('netplan', ['apply']);
      state.phase = 'CUTOVER_COMPLETE';
      appendLog(state, 'CUTOVER_COMPLETE', 'Migration complete', true);
      saveState(state);
      await auditLogger.log({ action: 'frr_confirm', user, details: 'migration complete', success: true });
      res.json({ success: true, state });
    } catch (err) {
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  router.post('/migration/rollback', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    const state = loadState();
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.flushHeaders();
    const write = (msg: string) => res.write(msg);
    try {
      write(`Rolling back from phase: ${state.phase}\n`);
      for (const f of ['60-open5gs-transit.yaml', '61-open5gs-dummies.yaml', '62-open5gs-cutover.yaml']) {
        const fp = `/proc/1/root/etc/netplan/${f}`;
        if (fs.existsSync(fp)) { fs.unlinkSync(fp); write(`Removed ${f}\n`); }
      }
      await nsenter('netplan', ['apply']);
      write('Netplan restored.\n');
      if (!['INIT', 'BACKUP_CREATED'].includes(state.phase)) {
        await new Promise<void>(resolve => {
          exec(`nsenter -t 1 -m -u -i -p -- systemctl stop frr`, () => resolve());
        });
        write('FRR stopped.\n');
      }
      const fresh: MigrationState = {
        phase: 'INIT', protocol: state.protocol, protocolConfig: state.protocolConfig,
        mgmtInterface: state.mgmtInterface, transitInterface: state.transitInterface,
        transitCidr: state.transitCidr, servicePlaneInterface: state.servicePlaneInterface,
        serviceMappings: state.serviceMappings, routeFilters: state.routeFilters ?? [], backupTimestamp: null,
        log: [], updatedAt: new Date().toISOString(),
      };
      appendLog(fresh, 'INIT', `Rolled back from ${state.phase}`, true);
      saveState(fresh);
      await auditLogger.log({ action: 'frr_rollback', user, details: `from ${state.phase}`, success: true });
      write('\n✅ Rollback complete.\n');
      res.end();
    } catch (err) {
      write(`\n❌ Rollback error: ${String(err)}\n`);
      res.end();
    }
  });

  // ── POST /api/frr/migration/rewind ───────────────────────────────────────────
  // Step state back to a specific phase WITHOUT touching the system.
  // Lets the user re-run a phase with corrected parameters.
  router.post('/migration/rewind', requireAdmin, (req: Request, res: Response) => {
    const { phase } = req.body as { phase: MigrationPhase };
    const validPhases: MigrationPhase[] = [
      'INIT', 'BACKUP_CREATED', 'FRR_INSTALLED', 'TRANSIT_CONFIGURED',
      'NEIGHBOR_UP', 'DUMMY_INTERFACES_CREATED', 'SERVICE_DUAL_STACK_ACTIVE',
      'LEGACY_INTERFACES_REMOVED',
    ];
    if (!validPhases.includes(phase)) {
      return res.status(400).json({ success: false, error: `Invalid rewind phase: ${phase}` });
    }
    try {
      const state = loadState();
      const prev = state.phase;
      state.phase = phase;
      appendLog(state, phase, `Rewound from ${prev} to ${phase} for re-execution`, true);
      saveState(state);
      res.json({ success: true, state });
    } catch (err) {
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  // ── POST /api/frr/route-filters ──────────────────────────────────────────────────────
  router.post('/route-filters', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    try {
      const state = loadState();
      // Back up previous filters before overwriting
      state.routeFilterBackup = state.routeFilters ?? [];
      state.routeFilters = req.body.filters ?? [];
      saveState(state);

      // If FRR is already running, regenerate and reload config immediately
      const activeOut = await new Promise<string>(resolve => {
        const c = exec(`nsenter -t 1 -m -u -i -p -- systemctl is-active frr`);
        let out = ''; c.stdout?.on('data', (d: Buffer) => { out += d.toString(); });
        c.on('close', () => resolve(out.trim()));
      });
      if (activeOut === 'active') {
        const config = await generateFrrConfig(state);
        fs.writeFileSync(HOST_FRR_CONF, config, 'utf-8');
        await new Promise<void>((resolve, reject) => {
          exec(`nsenter -t 1 -m -u -i -p -- systemctl restart frr`, (err) => err ? reject(err) : resolve());
        });
        // Give FRR a moment to come back up after restart
        await new Promise(r => setTimeout(r, 2000));
        await auditLogger.log({ action: 'frr_neighbor_config', user, details: 'route filters updated', success: true });
        res.json({ success: true, state, applied: true });
      } else {
        res.json({ success: true, state, applied: false });
      }
    } catch (err) { res.status(500).json({ success: false, error: String(err) }); }
  });

  // ── POST /api/frr/route-filters/preview ──────────────────────────────────────────
  router.post('/route-filters/preview', requireAdmin, async (req: Request, res: Response) => {
    try {
      const state = { ...loadState(), routeFilters: req.body.filters ?? [] };
      const config = await generateFrrConfig(state);
      res.json({ success: true, config });
    } catch (err) { res.status(500).json({ success: false, error: String(err) }); }
  });

  // ── POST /api/frr/route-filters/rollback ─────────────────────────────────────────
  router.post('/route-filters/rollback', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    try {
      const state = loadState();
      if (!state.routeFilterBackup) return res.status(400).json({ success: false, error: 'No backup to roll back to' });
      state.routeFilters = state.routeFilterBackup;
      state.routeFilterBackup = undefined;
      saveState(state);
      // Reload FRR with previous filters
      const config = await generateFrrConfig(state);
      fs.writeFileSync(HOST_FRR_CONF, config, 'utf-8');
      await new Promise<void>((resolve, reject) => {
        exec(`nsenter -t 1 -m -u -i -p -- systemctl restart frr`, (err) => err ? reject(err) : resolve());
      });
      await auditLogger.log({ action: 'frr_neighbor_config', user, details: 'route filters rolled back', success: true });
      res.json({ success: true, state, filters: state.routeFilters });
    } catch (err) { res.status(500).json({ success: false, error: String(err) }); }
  });

  // ── GET /api/frr/parse-running-config ────────────────────────────────────────
  // Parse the running FRR config into structured form for pre-populating the wizard
  router.get('/parse-running-config', async (_req: Request, res: Response) => {
    try {
      const { stdout: raw } = await nsenter('vtysh', ['-c', 'show running-config']).catch(() => ({ stdout: '' }));
      if (!raw) return res.json({ success: true, parsed: null });

      const parsed: Record<string, any> = { protocol: null };

      // EIGRP
      const eigrpAs = raw.match(/^router eigrp (\d+)/m);
      if (eigrpAs) {
        parsed.protocol = 'eigrp';
        parsed.as = parseInt(eigrpAs[1]);
        const net = raw.match(/^\s+network (\S+)/m);
        parsed.transitCidr = net?.[1] ?? '';
      }

      // OSPF
      const ospfPid = raw.match(/^router ospf (\d+)/m);
      if (ospfPid) {
        parsed.protocol = 'ospf';
        parsed.processId = parseInt(ospfPid[1]);
        const rid = raw.match(/ospf router-id (\S+)/);
        parsed.routerId = rid?.[1] ?? '';
        const areaMatch = raw.match(/ip ospf area (\S+)/);
        parsed.area = areaMatch?.[1] ?? '0';
        parsed.networkType = raw.includes('point-to-point') ? 'point-to-point' : 'broadcast';
        parsed.redistributeMethod = raw.includes('redistribute connected') ? 'redistribute' : 'network';
        const passiveMatches = [...raw.matchAll(/passive-interface (\S+)/g)];
        parsed.passiveInterfaces = passiveMatches.map(m => m[1]);
      }

      // BGP
      const bgpAs = raw.match(/^router bgp (\d+)/m);
      if (bgpAs) {
        parsed.protocol = 'bgp';
        parsed.localAs = parseInt(bgpAs[1]);
        const neighbor = raw.match(/neighbor (\S+) remote-as (\d+)/);
        parsed.peerIp = neighbor?.[1] ?? '';
        parsed.peerAs = neighbor ? parseInt(neighbor[2]) : 0;
        const multihop = raw.match(/ebgp-multihop (\d+)/);
        parsed.ebgpMultihop = multihop ? parseInt(multihop[1]) : 1;
        parsed.nextHopSelf = raw.includes('next-hop-self');
      }

      res.json({ success: true, parsed });
    } catch (err) {
      res.status(500).json({ success: false, error: String(err) });
    }
  });

  // ── POST /api/frr/reconfigure ───────────────────────────────────────────
  // Apply new FRR config to an already-running instance (skips migration phases)
  router.post('/reconfigure', requireAdmin, async (req: Request, res: Response) => {
    const user = (req as any).user?.username ?? 'unknown';
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.flushHeaders();
    const write = (msg: string) => res.write(msg);
    try {
      // Save new config to state
      const { mgmtInterface, transitInterface, transitCidr, servicePlaneInterface,
              serviceMappings, protocol, protocolConfig } = req.body;
      const state = loadState();
      state.mgmtInterface        = mgmtInterface;
      state.transitInterface     = transitInterface;
      state.transitCidr          = transitCidr;
      state.servicePlaneInterface = servicePlaneInterface;
      state.serviceMappings      = serviceMappings ?? [];
      state.protocol             = protocol;
      state.protocolConfig       = protocolConfig;
      saveState(state);

      // Backup current frr.conf first
      if (fs.existsSync(HOST_FRR_CONF)) {
        const ts = new Date().toISOString().replace(/[:.]/g, '-');
        fs.copyFileSync(HOST_FRR_CONF, `${HOST_FRR_CONF}.backup-${ts}`);
        write(`Backed up existing frr.conf to frr.conf.backup-${ts}\n`);
      }

      write('Generating new FRR config...\n');
      const config = await generateFrrConfig(state);
      write(config + '\n\n');

      write('Writing /etc/frr/frr.conf...\n');
      fs.writeFileSync(HOST_FRR_CONF, config, 'utf-8');

      // Enable correct daemon
      if (fs.existsSync(HOST_DAEMONS)) {
        let d = fs.readFileSync(HOST_DAEMONS, 'utf-8');
        d = d.replace(/^zebra=.*/m, 'zebra=yes');
        if (protocol === 'eigrp') d = d.replace(/^eigrpd=.*/m, 'eigrpd=yes');
        if (protocol === 'ospf')  d = d.replace(/^ospfd=.*/m,  'ospfd=yes');
        if (protocol === 'bgp')   d = d.replace(/^bgpd=.*/m,   'bgpd=yes');
        fs.writeFileSync(HOST_DAEMONS, d, 'utf-8');
        write('Daemons file updated.\n');
      }

      write('Reloading FRR...\n');
      await new Promise<void>((resolve, reject) => {
        exec(`nsenter -t 1 -m -u -i -p -- systemctl reload frr`, (err) => err ? reject(err) : resolve());
      });

      write('\n✅ FRR reconfigured successfully.\n');
      await auditLogger.log({ action: 'frr_neighbor_config', user, details: `reconfigure: ${protocol}`, success: true });
      res.end();
    } catch (err) {
      write(`\n❌ Error: ${String(err)}\n`);
      res.end();
    }
  });

  return router;
}
