import * as fs from 'fs/promises';
import * as path from 'path';
import pino from 'pino';

// The 7 NFs that expose Prometheus metrics in Open5GS
const METRICS_NFS = [
  { key: 'amf',  label: 'amf'  },
  { key: 'smf',  label: 'smf'  },
  { key: 'upf',  label: 'upf'  },
  { key: 'pcf',  label: 'pcf'  },
  { key: 'mme',  label: 'mme'  },
  { key: 'hss',  label: 'hss'  },
  { key: 'pcrf', label: 'pcrf' },
] as const;

export interface PrometheusTarget {
  address: string;
  port: number;
}

export class SyncPrometheusConfigUseCase {
  constructor(
    private readonly prometheusConfigPath: string,
    private readonly prometheusUrl: string,
    private readonly logger: pino.Logger,
  ) {}

  /**
   * Extract metrics address/port from a raw NF config object.
   * The rawYaml structure is { [nfKey]: { metrics: { server: [{ address, port }] } } }
   */
  private extractTarget(rawConfig: any, nfKey: string): PrometheusTarget | null {
    const server = rawConfig?.[nfKey]?.metrics?.server?.[0];
    if (!server?.address) return null;
    return {
      address: server.address,
      port: server.port ?? 9090,
    };
  }

  /**
   * Build the full prometheus.yml content from the current NF configs.
   * Preserves the global settings block — only scrape_configs is dynamic.
   */
  private buildPrometheusYml(targets: Record<string, PrometheusTarget>): string {
    const jobs = METRICS_NFS
      .filter(({ key }) => targets[key])
      .map(({ key, label }) => {
        const t = targets[key];
        return [
          `  - job_name: open5gs-${label}`,
          `    static_configs:`,
          `      - targets: ['${t.address}:${t.port}']`,
          `        labels:`,
          `          nf: ${label}`,
          `          generation: ${['amf', 'smf', 'upf', 'pcf'].includes(label) ? '5g' : '4g'}`,
        ].join('\n');
      });

    const scrapeConfigs = jobs.length > 0
      ? `scrape_configs:\n\n${jobs.join('\n\n')}\n`
      : `scrape_configs: []\n`;

    return [
      `# ─────────────────────────────────────────────────────────────────────`,
      `# Prometheus configuration for Open5GS NMS`,
      `# AUTO-GENERATED — do not edit manually.`,
      `# This file is regenerated by the NMS whenever metrics endpoints change.`,
      `# To make permanent changes, use the Metrics Endpoints page in the NMS UI.`,
      `# ─────────────────────────────────────────────────────────────────────`,
      ``,
      `global:`,
      `  scrape_interval:     15s`,
      `  evaluation_interval: 15s`,
      `  scrape_timeout:      10s`,
      ``,
      scrapeConfigs,
    ].join('\n');
  }

  /**
   * Write prometheus.yml and trigger a live reload via the Prometheus HTTP API.
   * Returns { reloaded: true } on success, { reloaded: false, error } on failure.
   * Never throws — Prometheus sync failure is non-fatal.
   */
  async execute(allConfigs: any): Promise<{ reloaded: boolean; error?: string }> {
    try {
      // 1. Extract targets from incoming configs
      const targets: Record<string, PrometheusTarget> = {};
      for (const { key } of METRICS_NFS) {
        const raw = allConfigs[key];
        const target = this.extractTarget(raw, key);
        if (target) {
          targets[key] = target;
        }
      }

      this.logger.info(
        { targets: Object.fromEntries(Object.entries(targets).map(([k, v]) => [k, `${v.address}:${v.port}`])) },
        'Syncing Prometheus config',
      );

      // 2. Build the new prometheus.yml content
      const content = this.buildPrometheusYml(targets);

      // 3. Write the file — overwrite in place so Prometheus reload picks it up correctly
      // NOTE: atomic rename (write tmp + rename) creates a new inode which confuses
      // Prometheus on Linux bind mounts. Direct overwrite keeps the same inode.
      const absPath = path.resolve(this.prometheusConfigPath);
      await fs.writeFile(absPath, content, 'utf-8');
      this.logger.info({ path: absPath }, 'prometheus.yml written');

      // 4. Trigger live reload via Prometheus HTTP API
      // POST /-/reload — requires --web.enable-lifecycle (already set in docker-compose)
      const reloadUrl = `${this.prometheusUrl}/-/reload`;
      const response = await fetch(reloadUrl, { method: 'POST', signal: AbortSignal.timeout(5000) });

      if (!response.ok) {
        const msg = `Prometheus reload HTTP ${response.status}`;
        this.logger.warn({ status: response.status, url: reloadUrl }, msg);
        return { reloaded: false, error: msg };
      }

      this.logger.info({ url: reloadUrl }, 'Prometheus reloaded successfully');
      return { reloaded: true };

    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      this.logger.warn({ err: msg }, 'Prometheus sync failed (non-fatal)');
      return { reloaded: false, error: msg };
    }
  }
}
