version: "3.8"

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    network_mode: host
    command: ["--bind_ip", "0.0.0.0"]
    volumes:
      - ./mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    network_mode: host
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://127.0.0.1:27017"
      ME_CONFIG_BASICAUTH: "false"
