import { useEffect, useState } from 'react';
import { Activity, Cpu, Download, HardDrive, Network, Play, RadioTower, RefreshCw, Server, Square, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { snmpApi, SnmpStats, SnmpStatus } from '../api/snmp';

const fmt = (n:number) => n >= 1e9 ? `${(n/1e9).toFixed(2)} GB` : n >= 1e6 ? `${(n/1e6).toFixed(1)} MB` : n >= 1e3 ? `${(n/1e3).toFixed(1)} KB` : `${n} B`;

export function SnmpPage(): JSX.Element {
  const [status,setStatus]=useState<SnmpStatus|null>(null); const [stats,setStats]=useState<SnmpStats|null>(null);
  const [community,setCommunity]=useState(''); const [network,setNetwork]=useState('127.0.0.1/32'); const [busy,setBusy]=useState(false);
  const refresh=async()=>{ try { const [s,m]=await Promise.all([snmpApi.status(),snmpApi.stats()]); setStatus(s); setStats(m); } catch { toast.error('Unable to refresh SNMP monitoring'); } };
  useEffect(()=>{ refresh(); const t=setInterval(refresh,15000); return()=>clearInterval(t); },[]);
  const install=async()=>{ setBusy(true); try { await snmpApi.install(community,network); toast.success('SNMP server installed and started'); await refresh(); } catch(e:any){toast.error(e.response?.data?.error||'Installation failed');} finally{setBusy(false);} };
  const action=async(a:'start'|'stop'|'restart')=>{setBusy(true);try{await snmpApi.action(a);toast.success(`SNMP ${a} successful`);await refresh();}catch{toast.error(`SNMP ${a} failed`);}finally{setBusy(false);}};
  const cards=[['CPU',stats?.cpuPercent??0,'%',Cpu],['RAM',stats?.memoryPercent??0,'%',HardDrive],['4G UEs',stats?.ue4g??0,'',Users],['5G UEs',stats?.ue5g??0,'',Users],['4G BBUs / eNBs',stats?.enb??0,'',RadioTower],['5G BBUs / gNBs',stats?.gnb??0,'',RadioTower]] as const;
  return <div className="p-6 space-y-6">
    <div className="flex items-start justify-between"><div><h1 className="text-2xl font-display font-semibold text-nms-text flex items-center gap-2"><Activity className="w-6 h-6 text-nms-accent"/>SNMP Monitoring</h1><p className="text-sm text-nms-text-dim mt-1">PRTG-ready host, network and Open5GS mobile-core sensors</p></div><button onClick={refresh} className="nms-btn-ghost flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Refresh</button></div>
    <div className="nms-card flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><div className={status?.active?'status-dot-active':'status-dot-inactive'}/><div><p className="font-semibold text-nms-text">Net-SNMP agent</p><p className="text-xs text-nms-text-dim">{status?.installed?(status.active?'Active on UDP/161':'Installed, stopped'):'Not installed'} · {status?.enabled?'starts at boot':'not enabled at boot'}</p></div></div><div className="flex gap-2"><a href={snmpApi.mibUrl} download className="nms-btn-ghost flex items-center gap-2"><Download className="w-4 h-4"/>Download MIB</a>{status?.installed?<><button disabled={busy||status.active} onClick={()=>action('start')} className="nms-btn-ghost flex items-center gap-1"><Play className="w-4 h-4"/>Start</button><button disabled={busy||!status.active} onClick={()=>action('stop')} className="nms-btn-ghost flex items-center gap-1 text-red-400"><Square className="w-4 h-4"/>Stop</button><button disabled={busy} onClick={()=>action('restart')} className="nms-btn-primary flex items-center gap-1"><RefreshCw className="w-4 h-4"/>Restart</button></>:null}</div></div>
    {!status?.installed&&<div className="nms-card"><h2 className="font-display font-semibold text-nms-text flex items-center gap-2"><Server className="w-5 h-5 text-nms-accent"/>Install the SNMP server</h2><p className="text-sm text-nms-text-dim mt-1">Installs net-snmp, creates a read-only SNMPv2c configuration, registers the Open5GS experimental MIB, then enables the service at boot. Restrict access to the exact monitoring network.</p><div className="grid md:grid-cols-2 gap-4 mt-4"><label className="text-xs text-nms-text-dim">Read-only community (8+ characters)<input type="password" autoComplete="new-password" placeholder="Choose a strong community" value={community} onChange={e=>setCommunity(e.target.value)} className="nms-input w-full mt-1 font-mono"/></label><label className="text-xs text-nms-text-dim">Allowed monitoring network (CIDR)<input placeholder="10.0.0.0/24" value={network} onChange={e=>setNetwork(e.target.value)} className="nms-input w-full mt-1 font-mono"/></label></div><button disabled={busy||community.length<8} onClick={install} className="nms-btn-primary mt-4">{busy?'Installing…':'Install and start SNMP'}</button></div>}
    <div className="grid sm:grid-cols-2 xl:grid-cols-6 gap-3">{cards.map(([label,value,suffix,Icon])=><div key={label} className="nms-card"><Icon className="w-4 h-4 text-nms-accent mb-2"/><p className="text-xs text-nms-text-dim">{label}</p><p className="text-2xl font-mono font-semibold text-nms-text">{value}{suffix}</p></div>)}</div>
    <div><h2 className="font-display font-semibold text-nms-text flex items-center gap-2 mb-3"><Network className="w-5 h-5 text-nms-accent"/>Network interfaces</h2><div className="nms-card p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-nms-text-dim bg-nms-surface-2"><th className="p-3">Interface</th><th className="p-3">State</th><th className="p-3">MTU</th><th className="p-3">RX</th><th className="p-3">TX</th></tr></thead><tbody>{stats?.interfaces.map(i=><tr key={i.name} className={`border-t border-nms-border/50 ${i.name==='ogstun'?'bg-nms-accent/5':''}`}><td className="p-3 font-mono font-semibold">{i.name}{i.name==='ogstun'&&<span className="ml-2 text-[10px] text-nms-accent">Open5GS tunnel</span>}</td><td className="p-3"><span className={i.state==='UP'?'text-nms-green':'text-nms-text-dim'}>{i.state}</span></td><td className="p-3 font-mono">{i.mtu}</td><td className="p-3 font-mono">{fmt(i.rxBytes)}</td><td className="p-3 font-mono">{fmt(i.txBytes)}</td></tr>)}</tbody></table></div><p className="text-xs text-nms-text-dim mt-2">PRTG can read every interface, including ogstun, through the standard IF-MIB. Open5GS-specific counters use the Net-SNMP experimental subtree 1.3.6.1.4.1.8072.9999.55555.</p></div>
  </div>;
}
